services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../backend/Orders.Api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Host=postgres;Database=orders;Username=postgres;Password=postgres
      - SERVICEBUS_CONNECTIONSTRING=${SERVICEBUS_CONNECTIONSTRING}
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      /bin/sh -c "
        dotnet Orders.Api.dll
      "

  worker:
    build: ../worker/Orders.Worker
    environment:
      - ConnectionStrings__Default=Host=postgres;Database=orders;Username=postgres;Password=postgres
      - SERVICEBUS_CONNECTIONSTRING=${SERVICEBUS_CONNECTIONSTRING}
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    command: >
      /bin/sh -c "
        sleep 5 && dotnet Orders.Worker.dll
      "