version: "3.9"
services:
  api:
    build: ../backend/Orders.Api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Host=postgres;Database=orders;Username=postgres;Password=postgres
    depends_on:
      - postgres

  worker:
    build: ../worker/Orders.Worker
    environment:
      - ConnectionStrings__Default=Host=postgres;Database=orders;Username=postgres;Password=postgres
    depends_on:
      - postgres
      - api

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
